GET http://localhost:3600/seller-pickup-locations/user/9

###
POST http://localhost:3600/seller-pickup-locations
Content-Type: application/json

{
    "user_id":9,
    "name":"Loja Centro",
    "street":"Rua A",
    "number":"100",
    "complement":"",
    "neighborhood":"Centro",
    "city":"Matão",
    "state":"SP",
    "zipcode":"15990-000",
    "active":true
}

###
PUT http://localhost:3600/seller-pickup-locations/1
Content-Type: application/json

{
    "name":"Loja Centro Atualizada",
    "street":"Rua B",
    "number":"200",
    "complement":"",
    "neighborhood":"Centro",
    "city":"Matão",
    "state":"SP",
    "zipcode":"15990-000",
    "active":true
}

###
DELETE http://localhost:3600/seller-pickup-locations/2